[project]
name = "open-gptlive-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ali Tavallaie", email = "a.tavallaie@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115,<1",
    "faster-whisper>=1.1,<2",
    "numpy>=2,<3",
    "onnxruntime>=1.20,<2",
]

[project.scripts]
open-gptlive-poc = "open_gptlive_poc:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
